services:
  warehouse:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=qbo_raw
    volumes:
      - "./warehouse_data:/var/lib/postgressql/data:rw"
    ports:
      - "5432:5432"
  warehouseui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - "./warehouse_ui_data:/var/lib/pgadmin"
    ports:
      - "8081:80"
  scheduler:
    image: mageai/mageai
    volumes:
      - "./scheduler_data:/home/src"
    ports:
      - "6789:6789"
    command: /app/run_app.sh mage start scheduler

    